// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKFSgQ4wRhOfUxnTMNl9EpaY6_jel5ZJg',
    appId: '1:853737485309:web:503aec17bb8d9d6a66df94',
    messagingSenderId: '853737485309',
    projectId: 'downcare-5e8e7',
    authDomain: 'downcare-5e8e7.firebaseapp.com',
    storageBucket: 'downcare-5e8e7.firebasestorage.app',
    measurementId: 'G-58XYVJGD29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxIth9pHDsfgGZkA9YxKwOZvfX-66sKU8',
    appId: '1:853737485309:android:fb2f7a36adcebf8866df94',
    messagingSenderId: '853737485309',
    projectId: 'downcare-5e8e7',
    storageBucket: 'downcare-5e8e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ9z4Jo2CKvuDq1kT88NQS9oNGSsUWKLE',
    appId: '1:853737485309:ios:a70862569f37054766df94',
    messagingSenderId: '853737485309',
    projectId: 'downcare-5e8e7',
    storageBucket: 'downcare-5e8e7.firebasestorage.app',
    iosBundleId: 'com.example.stepUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ9z4Jo2CKvuDq1kT88NQS9oNGSsUWKLE',
    appId: '1:853737485309:ios:a70862569f37054766df94',
    messagingSenderId: '853737485309',
    projectId: 'downcare-5e8e7',
    storageBucket: 'downcare-5e8e7.firebasestorage.app',
    iosBundleId: 'com.example.stepUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKFSgQ4wRhOfUxnTMNl9EpaY6_jel5ZJg',
    appId: '1:853737485309:web:6f51b0cf407d0e7d66df94',
    messagingSenderId: '853737485309',
    projectId: 'downcare-5e8e7',
    authDomain: 'downcare-5e8e7.firebaseapp.com',
    storageBucket: 'downcare-5e8e7.firebasestorage.app',
    measurementId: 'G-2ZD1SS9642',
  );
}
